sudo: required

services:
  - docker

before_script:
  - docker run --name test-db --expose 5432:5432 --detach postgres:latest
  - docker cp init.sql test-db:/tmp

script:
  - ./test.sh test-db 1

after_script:
  - docker stop test-db
  - docker rm test-db
