sudo: required

services:
  - docker

before_script:
  - docker run --name test-db --detach postgres:latest

script:
  - docker cp init.sql test-db:/tmp && ./test.sh test-db

after_script:
  - docker stop test-db && docker rm test-db